# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhche
type: Opaque
data:
  CHE_FABRIC8_MULTITENANT: "true"
  CHE_CORE_JSONRPC_PROCESSOR__MAX__POOL__SIZE: "2000"
  CHE_KEYCLOAK_CLIENT__ID: "che-public"
  CHE_KEYCLOAK_OIDC__PROVIDER: "NULL"
  CHE_KEYCLOAK_REALM: "che"
  CHE_KEYCLOAK_USE__NONCE: "false"
  CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "1"
  CHE_LOGS_DIR: "/data/logs"
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "false"
  CHE_INFRA_OPENSHIFT_TLS__ENABLED: "false"
  JAVA_OPTS: "-XX:+UseParallelGC -XX:MinHeapFreeRatio=25 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms50m -Xmx180m -Dfile.encoding=UTF8"
  CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS: "900000"
  CHE_WORKSPACE_LOGS_ROOT__DIR: "/workspace_logs"
  CHE_WORKSPACE_SERVER_PING__INTERVAL__MILLISECONDS: "500"
  CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD: "1"
  CHE_WORKSPACE_JAVA__OPTIONS: "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m"
  CHE_WORKSPACE_AUTO__START: "false"
  CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN: "5"
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: "common"
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "true"
  CHE_LOCAL_CONF_DIR: "/etc/conf"
  CHE_LOG_LEVEL: "INFO"
  CHE_MULTIUSER: "true"
  CHE_DEBUG_SERVER: "true"
  CHE_WORKSPACE_DEFAULT__MEMORY__MB: "2400"
  CHE_LIMITS_WORKSPACE_ENV_RAM: "2400mb"
  CHE_WORKSPACE_STORAGE: "/home/user/che/workspaces"
