# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
kind: Template
apiVersion: v1
metadata:
  labels:
    app: rhche
  name: rhche
  annotations:
    description: Che
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: rhche
    name: rhche
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: rhche
    labels:
      app: rhche
  roleRef:
    name: admin
  subjects:
  - kind: ServiceAccount
    name: rhche
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rhche
    name: rhche-host
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: rhche
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: rhche
    name: rhche
  spec:
    to:
      kind: Service
      name: rhche-host
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: rhche
    name: rhche
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: rhche
    strategy:
      type: ${STRATEGY}
    template:
      metadata:
        labels:
          app: rhche
      spec:
        containers:
        - env:
          - name: CHE_API
            value: "${PROTOCOL}://rhche-${NAMESPACE}.${ROUTING_SUFFIX}/api"
          - name: CHE_FABRIC8_AUTH_ENDPOINT
            value: ${CHE_FABRIC8_AUTH_ENDPOINT}
          - name: CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL
            value: ${CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL}
          - name: CHE_FABRIC8_STANDALONE
            value: "true"
          - name: CHE_FABRIC8_USER__SERVICE_ENDPOINT
            value: ${CHE_FABRIC8_USER__SERVICE_ENDPOINT}
          - name: CHE_HOST
            value: "rhche-${NAMESPACE}.${ROUTING_SUFFIX}"
          - name: CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL
            value: "${PROTOCOL}://rhche-${NAMESPACE}.${ROUTING_SUFFIX}/agent-binaries/linux_amd64/bootstrapper/bootstrapper"
          - name: CHE_INFRA_OPENSHIFT_PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CHE_INFRASTRUCTURE_ACTIVE
            value: "openshift"
          - name: CHE_KEYCLOAK_AUTH__SERVER__URL
            value: "${CHE_KEYCLOAK_AUTH__SERVER__URL}"
          - name: CHE_KEYCLOAK_GITHUB_ENDPOINT
            value: ${CHE_KEYCLOAK_AUTH__SERVER__URL}/realms/che/broker/github/token
          - name: CHE_OAUTH_SERVICE__MODE
            value: "embedded"
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_ID
            value: NULL
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_SECRET
            value: NULL
          - name: CHE_PORT
            value: "8080"
          - name: CHE_WEBSOCKET_ENDPOINT
            value: "${WS_PROTOCOL}://rhche-${NAMESPACE}.${ROUTING_SUFFIX}/api/websocket"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PROTOCOL
            value: "${PROTOCOL}"
          - name: ROUTING_SUFFIX
            value: "${ROUTING_SUFFIX}"
          - name: CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB
            value: "150"
          - name: CHE_SERVER_SECURE__EXPOSER_JWTPROXY_MEMORY__LIMIT
            value: "150mb"
          envFrom:
          - configMapRef:
              name: rhche
          image: ${IMAGE_RH_CHE}:${RH_CHE_VERSION}
          imagePullPolicy: "${PULL_POLICY}"
          livenessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: rhche
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8000
            name: http-debug
          - containerPort: 8888
            name: jgroups-ping
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 60
          resources:
            limits:
              memory: 750Mi
            requests:
              memory: 256Mi
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
        restartPolicy: Always
        serviceAccountName: rhche
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
parameters:
- name: ROUTING_SUFFIX
  displayName: Routing suffix of your OpenShift cluster
  description: This is the suffix appended to routes in your OpenShift cluster <route>-<project>.<routing_suffix>
- name: RH_CHE_VERSION
  displayName: Eclipse Che version
  description: Eclipse Che version which defaults to nightly
  value: latest
- name: IMAGE_RH_CHE
  displayName: RhChe server image
  description: RhChe server Docker image.
  value: quay.io/openshiftio/che-rh-che-server
- name: PROTOCOL
  displayName: https or http protocol
  description: Protocol to be used in Che communications
  value: http
- name: WS_PROTOCOL
  displayName: wss or ws
  description: Websocket protocol to be used in Che communications. Defaults to ws. Set to wss only if TLS is true and https protocol is defined
  value: ws
- name: CHE_KEYCLOAK_AUTH__SERVER__URL
  displayName: Identity provider URL
  description: URL of a remote identity provider. Defaults to Keycloak bundled with Che multi user
  value: '${PROTOCOL}://keycloak-${NAMESPACE}.${ROUTING_SUFFIX}/auth'
- name: STRATEGY
  displayName: Update Strategy
  description: Che server update strategy. Defaults to Recreate. Use Rolling only if Che deployment does not use PVC
  value: 'Rolling'
- name: PULL_POLICY
  displayName: Che server image pull policy
  description: Pull the image only if not present in the local registry by default. Can be 'Always' and 'Never'
  value: 'IfNotPresent'
- name: CHE_FABRIC8_USER__SERVICE_ENDPOINT
  displayName: User Service Endpoint
  description: URL of the user services API endpoint
  value: '${PROTOCOL}://api-${NAMESPACE}.${ROUTING_SUFFIX}/api/user/services'
- name: CHE_FABRIC8_AUTH_ENDPOINT
  displayName: Auth Service Endpoint
  description: URL of the auth API endpoint
  value: '${PROTOCOL}://auth-${NAMESPACE}.${ROUTING_SUFFIX}'
- name: CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL
  displayName: OpenShift Online Proxy Service
  description: URL of the OpenShift Online Proxy service
  value: '${PROTOCOL}://f8osoproxy-${NAMESPACE}.${ROUTING_SUFFIX}'
