# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
kind: Template
apiVersion: v1
metadata:
  labels:
    app: rhche
  name: rhche
objects:
- apiVersion: v1
  kind: ServiceAccount
  imagePullSecrets:
  - name: quay.io
  metadata:
    labels:
      app: rhche
    name: rhche
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rhche
    name: rhche-host
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 8087
      protocol: TCP
      targetPort: 8087
    selector:
      app: rhche
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: rhche
    name: rhche
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: rhche-host
    port:
      targetPort: http
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: rhche
    name: rhche
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: rhche
    strategy:
      rollingParams:
        timeoutSeconds: 10000
      type: Rolling
    template:
      metadata:
        labels:
          app: rhche
      spec:
        containers:
        - env:
          - name: CHE_API
            valueFrom:
              configMapKeyRef:
                key: CHE_API
                name: rhche
          - name: CHE_CORE_JSONRPC_PROCESSOR__MAX__POOL__SIZE
            valueFrom:
              configMapKeyRef:
                key: CHE_CORE_JSONRPC_PROCESSOR__MAX__POOL__SIZE
                name: rhche
          - name: CHE_CORS_ENABLED
            valueFrom:
              configMapKeyRef:
                key: CHE_CORS_ENABLED
                name: rhche
          - name: CHE_DEBUG_SERVER
            valueFrom:
              configMapKeyRef:
                key: CHE_DEBUG_SERVER
                name: rhche
          - name: CHE_FABRIC8_ANALYTICS_SEGMENT__WRITE__KEY
            valueFrom:
              configMapKeyRef:
                key: CHE_FABRIC8_ANALYTICS_SEGMENT__WRITE__KEY
                name: rhche
          - name: CHE_FABRIC8_ANALYTICS_WOOPRA__DOMAIN
            valueFrom:
              configMapKeyRef:
                key: CHE_FABRIC8_ANALYTICS_WOOPRA__DOMAIN
                name: rhche
          - name: CHE_FABRIC8_AUTH_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: CHE_FABRIC8_AUTH_ENDPOINT
                name: rhche
          - name: CHE_FABRIC8_END2END_PROTECT_VERIFY__WITH__IP
            valueFrom:
              configMapKeyRef:
                key: CHE_FABRIC8_END2END_PROTECT_VERIFY__WITH__IP
                name: rhche
          - name: CHE_FABRIC8_END2END_PROTECT_SECRET__KEY
            valueFrom:
              secretKeyRef:
                key: secret-key
                name: rhche-end2end-protection
                optional: true
          - name: CHE_FABRIC8_END2END_PROTECT_SITE__KEY
            valueFrom:
              secretKeyRef:
                key: site-key
                name: rhche-end2end-protection
                optional: true
          - name: CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL
            valueFrom:
              configMapKeyRef:
                key: CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL
                name: rhche
          - name: CHE_FABRIC8_MULTITENANT
            valueFrom:
              configMapKeyRef:
                key: CHE_FABRIC8_MULTITENANT
                name: rhche
          - name: CHE_FABRIC8_USER__SERVICE_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: CHE_FABRIC8_USER__SERVICE_ENDPOINT
                name: rhche
          - name: CHE_HOST
            valueFrom:
              configMapKeyRef:
                key: CHE_HOST
                name: rhche
          - name: CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL
            valueFrom:
              configMapKeyRef:
                key: CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL
                name: rhche
          - name: CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN
            valueFrom:
              configMapKeyRef:
                key: CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN
                name: rhche
          - name: CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS
            valueFrom:
              configMapKeyRef:
                key: CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS
                name: rhche
          - name: CHE_INFRA_KUBERNETES_PVC_QUANTITY
            valueFrom:
              configMapKeyRef:
                key: CHE_INFRA_KUBERNETES_PVC_QUANTITY
                name: rhche
          - name: CHE_INFRA_KUBERNETES_PVC_STRATEGY
            valueFrom:
              configMapKeyRef:
                key: CHE_INFRA_KUBERNETES_PVC_STRATEGY
                name: rhche
          - name: CHE_INFRA_KUBERNETES_TRUST__CERTS
            valueFrom:
              configMapKeyRef:
                key: CHE_INFRA_KUBERNETES_TRUST__CERTS
                name: rhche
          - name: CHE_INFRA_OPENSHIFT_PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CHE_INFRA_OPENSHIFT_TLS__ENABLED
            valueFrom:
              configMapKeyRef:
                key: CHE_INFRA_OPENSHIFT_TLS__ENABLED
                name: rhche
          - name: CHE_INFRASTRUCTURE_ACTIVE
            value: "openshift"
          - name: CHE_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.password
                  name: rhche
          - name: CHE_JDBC_URL
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.url
                  name: rhche
          - name: CHE_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.username
                  name: rhche
          - name: CHE_KEYCLOAK_AUTH__SERVER__URL
            valueFrom:
              configMapKeyRef:
                key: CHE_KEYCLOAK_AUTH__SERVER__URL
                name: rhche
          - name: CHE_KEYCLOAK_CLIENT__ID
            valueFrom:
              configMapKeyRef:
                key: CHE_KEYCLOAK_CLIENT__ID
                name: rhche
          - name: CHE_KEYCLOAK_GITHUB_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: CHE_KEYCLOAK_GITHUB_ENDPOINT
                name: rhche
          - name: CHE_KEYCLOAK_JS__ADAPTER__URL
            valueFrom:
              configMapKeyRef:
                key: CHE_KEYCLOAK_JS__ADAPTER__URL
                name: rhche
          - name: CHE_KEYCLOAK_OIDC__PROVIDER
            valueFrom:
              configMapKeyRef:
                key: CHE_KEYCLOAK_OIDC__PROVIDER
                name: rhche
          - name: CHE_KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                key: CHE_KEYCLOAK_REALM
                name: rhche
          - name: CHE_KEYCLOAK_USE__NONCE
            valueFrom:
              configMapKeyRef:
                key: CHE_KEYCLOAK_USE__NONCE
                name: rhche
          - name: CHE_LIMITS_USER_WORKSPACES_RUN_COUNT
            valueFrom:
              configMapKeyRef:
                key: CHE_LIMITS_USER_WORKSPACES_RUN_COUNT
                name: rhche
          - name: CHE_LIMITS_WORKSPACE_ENV_RAM
            valueFrom:
              configMapKeyRef:
                key: CHE_LIMITS_WORKSPACE_ENV_RAM
                name: rhche
          - name: CHE_LOCAL_CONF_DIR
            valueFrom:
              configMapKeyRef:
                key: CHE_LOCAL_CONF_DIR
                name: rhche
          - name: CHE_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                key: CHE_LOG_LEVEL
                name: rhche
          - name: CHE_LOGS_APPENDERS_IMPL
            valueFrom:
              configMapKeyRef:
                key: CHE_LOGS_APPENDERS_IMPL
                name: rhche
          - name: CHE_LOGS_DIR
            valueFrom:
              configMapKeyRef:
                key: CHE_LOGS_DIR
                name: rhche
          - name: CHE_LOGS_SENTRY_LEVEL
            valueFrom:
              configMapKeyRef:
                key: CHE_LOGS_SENTRY_LEVEL
                name: rhche
          - name: CHE_METRICS_ENABLED
            valueFrom:
              configMapKeyRef:
                key: CHE_METRICS_ENABLED
                name: rhche
          - name: CHE_MULTIUSER
            valueFrom:
              configMapKeyRef:
                key: CHE_MULTIUSER
                name: rhche
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                  key: service.account.id
                  name: rhche
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                  key: service.account.secret
                  name: rhche
          - name: CHE_PORT
            valueFrom:
              configMapKeyRef:
                key: CHE_PORT
                name: rhche
          - name: CHE_SYSTEM_ADMIN__NAME
            valueFrom:
              configMapKeyRef:
                key: CHE_SYSTEM_ADMIN__NAME
                name: rhche
          - name: CHE_SYSTEM_SUPER__PRIVILEGED__MODE
            valueFrom:
              configMapKeyRef:
                key: CHE_SYSTEM_SUPER__PRIVILEGED__MODE
                name: rhche
          - name: CHE_WORKSPACE_PLUGIN__REGISTRY__URL
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_PLUGIN__REGISTRY__URL
                name: rhche
          - name: CHE_PREDEFINED_STACKS_RELOAD__ON__START
            valueFrom:
              configMapKeyRef:
                key: CHE_PREDEFINED_STACKS_RELOAD__ON__START
                name: rhche
          - name: CHE_WEBSOCKET_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: CHE_WEBSOCKET_ENDPOINT
                name: rhche
          - name: CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS
                name: rhche
          - name: CHE_WORKSPACE_AUTO__START
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_AUTO__START
                name: rhche
          - name: CHE_WORKSPACE_DEFAULT__MEMORY__MB
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_DEFAULT__MEMORY__MB
                name: rhche
          - name: CHE_WORKSPACE_JAVA__OPTIONS
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_JAVA__OPTIONS
                name: rhche
          - name: CHE_WORKSPACE_LOGS_ROOT__DIR
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_LOGS_ROOT__DIR
                name: rhche
          - name: CHE_WORKSPACE_SERVER_PING__INTERVAL__MILLISECONDS
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_SERVER_PING__INTERVAL__MILLISECONDS
                name: rhche
          - name: CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD
                name: rhche
          - name: CHE_WORKSPACE_STORAGE
            valueFrom:
              configMapKeyRef:
                key: CHE_WORKSPACE_STORAGE
                name: rhche
          - name: CHE_WSAGENT_CORS_ALLOWED__ORIGINS
            valueFrom:
              configMapKeyRef:
                key: CHE_WSAGENT_CORS_ALLOWED__ORIGINS
                name: rhche
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                key: JAVA_OPTS
                name: rhche
          - name: SENTRY_DSN
            valueFrom:
              configMapKeyRef:
                key: SENTRY_DSN
                name: rhche
          - name: SENTRY_STACKTRACE_APP_PACKAGES
            valueFrom:
              configMapKeyRef:
                key: SENTRY_STACKTRACE_APP_PACKAGES
                name: rhche
          - name: SENTRY_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                key: SENTRY_ENVIRONMENT
                name: rhche
          - name: SENTRY_RELEASE
            value: ${IMAGE_TAG}
          - name: CHE_INFRA_KUBERNETES_SERVICE__ACCOUNT__NAME
            value: "che-workspace"
          - name: CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB
            value: "150"
          - name: CHE_SERVER_SECURE__EXPOSER_JWTPROXY_MEMORY__LIMIT
            value: "150mb"
          - name: CHE_WORKSPACE_PLUGIN__BROKER_THEIA__REMOTE_IMAGE
            value: "wsskeleton/che-plugin-broker:theia-broker"
          - name: CHE_WORKSPACE_PLUGIN__BROKER_THEIA_IMAGE
            value: "wsskeleton/che-plugin-broker:theia-broker-2"
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: rhche
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 8087
            name: metrics
          - containerPort: 8000
            name: http-debug
          readinessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 60
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 256Mi
        serviceAccountName: rhche
    triggers:
    - type: ConfigChange
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-che-rh-che-server
- name: IMAGE_TAG
  value: latest
